"""
Unit tests for dynamic title generation.

The old YouTubeUpdaterCore._generate_dynamic_title method no longer exists.
Dynamic titles are now generated by DefaultTitleGenerator in
youtube_updater/core/default_title_generator.py.

These tests verify DefaultTitleGenerator.generate_title returns correct titles
based on day-of-week and time, by patching
youtube_updater.core.default_title_generator.datetime.
"""

import unittest
from datetime import datetime, timezone
from unittest.mock import patch, MagicMock
import pytz

from youtube_updater.core.default_title_generator import DefaultTitleGenerator


class TestDynamicTitleViaPatch(unittest.TestCase):
    """Test DefaultTitleGenerator.generate_title with patched datetime.now."""

    def _make_eastern_dt(self, year, month, day, hour, minute=0):
        """Return a timezone-aware datetime in US/Eastern."""
        est = pytz.timezone("US/Eastern")
        return est.localize(datetime(year, month, day, hour, minute, 0))

    def test_generate_title_saturday_after_5pm_returns_vespers(self):
        """Test Saturday at 6 PM Eastern returns Vespers suffix."""
        saturday_6pm_est = self._make_eastern_dt(2024, 3, 23, 18)  # Saturday

        with patch(
            "youtube_updater.core.default_title_generator.datetime"
        ) as mock_dt:
            mock_dt.now.return_value = saturday_6pm_est
            gen = DefaultTitleGenerator()
            title = gen.generate_title()

        self.assertEqual(title, "Saturday, March 23, 2024 - Vespers and Midnight Praises")

    def test_generate_title_saturday_before_5pm_returns_divine_liturgy(self):
        """Test Saturday at 10 AM Eastern returns Divine Liturgy suffix."""
        saturday_10am_est = self._make_eastern_dt(2024, 3, 23, 10)  # Saturday

        with patch(
            "youtube_updater.core.default_title_generator.datetime"
        ) as mock_dt:
            mock_dt.now.return_value = saturday_10am_est
            gen = DefaultTitleGenerator()
            title = gen.generate_title()

        self.assertEqual(title, "Saturday, March 23, 2024 - Divine Liturgy")

    def test_generate_title_saturday_at_1145pm_returns_vespers(self):
        """Test Saturday at 11:45 PM Eastern still returns Vespers (boundary)."""
        saturday_1145pm_est = self._make_eastern_dt(2024, 3, 23, 23, 45)

        with patch(
            "youtube_updater.core.default_title_generator.datetime"
        ) as mock_dt:
            mock_dt.now.return_value = saturday_1145pm_est
            gen = DefaultTitleGenerator()
            title = gen.generate_title()

        self.assertEqual(title, "Saturday, March 23, 2024 - Vespers and Midnight Praises")

    def test_generate_title_not_saturday_returns_divine_liturgy(self):
        """Test a weekday (Wednesday) returns Divine Liturgy."""
        wednesday_8pm_est = self._make_eastern_dt(2024, 3, 20, 20)  # Wednesday

        with patch(
            "youtube_updater.core.default_title_generator.datetime"
        ) as mock_dt:
            mock_dt.now.return_value = wednesday_8pm_est
            gen = DefaultTitleGenerator()
            title = gen.generate_title()

        self.assertEqual(title, "Wednesday, March 20, 2024 - Divine Liturgy")

    def test_generate_title_sunday_returns_divine_liturgy(self):
        """Test Sunday returns Divine Liturgy."""
        sunday_10am_est = self._make_eastern_dt(2024, 3, 24, 10)  # Sunday

        with patch(
            "youtube_updater.core.default_title_generator.datetime"
        ) as mock_dt:
            mock_dt.now.return_value = sunday_10am_est
            gen = DefaultTitleGenerator()
            title = gen.generate_title()

        self.assertEqual(title, "Sunday, March 24, 2024 - Divine Liturgy")

    def test_generate_title_uses_generator_timezone(self):
        """Test that the generator uses the configured timezone for decisions."""
        # US/Pacific -- Saturday at 6 PM Pacific (9 PM Eastern, still Saturday)
        pacific = pytz.timezone("US/Pacific")
        saturday_6pm_pacific = pacific.localize(datetime(2024, 3, 23, 18, 0, 0))

        with patch(
            "youtube_updater.core.default_title_generator.datetime"
        ) as mock_dt:
            mock_dt.now.return_value = saturday_6pm_pacific
            gen = DefaultTitleGenerator(timezone="US/Pacific")
            title = gen.generate_title()

        self.assertEqual(title, "Saturday, March 23, 2024 - Vespers and Midnight Praises")


if __name__ == "__main__":
    unittest.main()
